### ISSUE TITLE
lightweight monitoring page to be displayed by Raspberry Pi

### ISSUE THREAD

**Issue by agentsmithitaly** [OctoPrint/OctoPrint#215]
I'd like to interact with OctoPrint UI within a 800x480 7" touchscreen display connected to the Raspberry Pi
Unfortunately when opened in Chromium within Raspbian, the interface is very sluggish, and sucks all CPU resources even if overclocked to 1 Ghz, probably due to the nice JS effects and AJAX comm method Octoprint utilizes that are too heavy for the mighty RPi.

What about an additional lightweight page that:
- don't uses JS effects, animations
- bigger Print, Pause, Cancel and Emergency Stop buttons 
- groups temperature and controls in one page, no Gcode or terminal views
- is widescreen optimized

In this way the printer would have a handy control panel, while full-fledged Octoprint UI would be available when away from the printer

Here you see current view (75%, fullscreen) displayed on the touchscreen
![20130803_004552](https://f.cloud.github.com/assets/5151309/904639/3d98edb4-fbcf-11e2-8144-8d463a7144f0.jpg)

I'd be more willing to help if necessary, I'm quite new to Github and Python, but I'm a web designer :)

**Comment by bolsoncerrado** [comment]
I do have a touchscreen at 800x480 too, I'd like to either contribute or work onto a responsive GUI too.

Let's move! ;)

**Comment by flyswatter** [comment]
Based on some discussions I was having related to my idea to create an [OctoPrintUI](https://github.com/flyswatter/OctoPrintUI).

Did some experiments, and there’s good news and bad news about modding the existing application:

The good news is that yes, we’re looking at Knockout as the core application, which means that adding your own UI for functions on the current application is as easy as copying the “data-bind” attributes from the old UI, and adding them to your own elements, ideally documenting them each, so there can be a nice guide to building fresh UIs for people in the future.

For simpler mods of the UI, you can always just do what agentsmithitaly did, and just modify the OctoPi templates, just trimming it down to what you want.  You could go even further by removing bootstrap themes, but you could also go further by adding your own chunks of interface, just copying the “data-bind” attributes, because those are the parts with all the magic.

The snag is that because of the framework he was using on his server, and it’s using these “jinja2” templates to insert some chunks of code (the disconnected dialog and settings box), so until someone re-writes those two boxes to be client-side, the simple mods will need to exist in this jinja templates folder.

So, the good and the bad:

1.  Very easy to make simple mods of.
2.  Great potential to use its foundation for a new approach to the UI.
3.  Some extraction/reorganization needed to realize that second benefit.

Anyways, I might do some more prodding on #3 today, but I have some other things I need to get to for now.

Good luck!

-Dan

**Comment by agentsmithitaly** [comment]
My templates hack did its job but on a slow box like a Raspberry Pi it
means lots of lag, plus after a couple of days the client would lose
connection to the server. Nothing that a simple browser refresh could
solve, but when it's running fullscreen there is no refresh button :(

A novel approach could be a simpler monitoring UI that hooks to OctoPrint
server through its API.
It could be written in either in JS or PyGame removing the need for a
browser.

**Comment by nophead** [comment]
Have you seen OctoPiPanel?

**Comment by flyswatter** [comment]
Yeah, funny you should mention it right after @agentsmithitaly suggested PyGame, since it's a PyGame application.

My own expertise is more in web interfaces, and those seem more universally portable to me, so I'll keep my own efforts in that domain.

**Comment by agentsmithitaly** [comment]
Cool, seems I could have some fun testing OctoPrintUI and OctoPiPanel! I
will provide feedback then.

Seems OctoPiPanel is created around PiTFT which is a 320x240 display.
Problem of PyGame applications is that they are tied to the screen
resolution they were programmed for.

**Comment by flyswatter** [comment]
Sorry, I don't think OctoPrintUI is quite ready for testing yet, it definitely represents a work in progress, extracting the relevant code, throwing away the code that isn't.  It could be longer term, and I haven't had a lot of gumption ever since that TFT I got turned out to not be a touchscreen..

**Comment by moritzmhmk** [comment]
also see https://github.com/foosel/OctoPrint/issues/805#issuecomment-141433245

**Comment by LazeMSS** [comment]
There are many new plugins that can do this like:
https://plugins.octoprint.org/plugins/dashboard/
https://plugins.octoprint.org/plugins/customcss/
https://plugins.octoprint.org/plugins/uicustomizer/
