### ISSUE TITLE
Baud rate 250000 does not work

### ISSUE THREAD

**Issue by guysoft** [OctoPrint/OctoPrint#222]
Tried connecting an arduino-based printer, which for some strange reason is set to baud rate 250000, this was the output:

```
Changing monitoring state from 'Offline' to 'Opening serial port'
Connecting to: /dev/ttyACM0
Unexpected error while connecting to serial port: /dev/ttyACM0 ValueError: 'Failed to set custom baud rate: 250000' @ comm.py:_monitor:479
Failed to open serial port (/dev/ttyACM0)
Changing monitoring state from 'Opening serial port' to 'Error: Failed to autodetect...'
```

Would love to provide any additional information to solve this problem.

**Comment by korneelb** [comment]
issue is back.. 

unexpected error while connecting to serial port: /dev/ttyACM0 ValueError: 'Failed to set custom baud rate: 250000' @ comm.py:_openSerial:1206
Changing monitoring state from 'Opening serial port' to 'Error: Failed to open serial port, permissions correct?'

latest OctoPi image and latest Octoprint devel build

**Comment by foosel** [comment]
That's a problem of the OctoPi image, not OctoPrint. OctoPrint can only use pyserial, but if that doesn't support 250k, there's nothing OctoPrint can do about it.

**Comment by korneelb** [comment]
you are right. i opened a bug on the OctoPi page. i assumed it was an OctoPrint issue.

**Comment by foosel** [comment]
If you give me the ticket number, I might be able to add a small hint for Guy how to fix it, I ran into the same issue with some internal development builds.

**Comment by korneelb** [comment]
thanks it's https://github.com/guysoft/OctoPi/issues/84

**Comment by RishiGupta12** [comment]
Is it possible to invoke java program from OctoPrint. I was able to set 250000 custom baudrate in java program http://www.embeddedunveiled.com/set-custom-baud-rate

**Comment by guysoft** [comment]
No, OctoPrint is a python program. Did you try the last nightly? We pushed a fix for this

**Comment by foosel** [comment]
To elaborate on this: OctoPrint in theory could of course call a java program (just as it can call a bash script or any other type of executable, e.g. for handling certain events or via the system actions). However, the communication layer within OctoPrint that is responsible for connecting to the printer is purely python based. A fix for the problem exists, like @guysoft writes it also has been applied on OctoPi, and besides this is the wrong bug tracker in any case since as I stated above OctoPrint merrily uses pyserial - OctoPrint can't do anything about if it that's a wrong version.

**Comment by guysoft** [comment]
I suggest we close here and continue at https://github.com/guysoft/OctoPi/issues/84
