### ISSUE TITLE
[Request] Allow users to browse most popular / trending plugins

### ISSUE THREAD

**Issue by chatrat12** [OctoPrint/OctoPrint#2765]
@foosel, in your latest live stream you talked about how you've implemented a new tracking system to collect information about OctoPrint instances in the latest maintenance/devel branches. I think it would awesome if plugin identifiers were compared against the plugin repo to inform the user about what the hottest plugins are. I've been a long time OctoPrint user and I just learned about OctoLapse though social media. I think it would be cool if a plugin that powerful and useful was easily discoverable to OctoPrint users straight out of the box. I'm still discovering useful plugins, but that is happening through community interactions.  I know this would have to be down the road once the collection of data has matured, and perhaps you have concerns about using that data for this purpose? I personally feel like it would be a huge boost the the OctoPrint experience :)

**Comment by foosel** [comment]
That is actually the reason why I want to track installed plugins. Currently the system only supports tracking actual plug-in installs (and uninstalls and enabling and disabling) when they take place though, I don't track the full plug-in list on eg startup since the way I built this tracker imposes certain limitations on how much data can be sent. But this could still be changed down the road.

For now I first want to see if people are actually open to this kind of opt-in anonymous usage tracking. It wouldn't make much sense to setup a complex infrastructure now to base things like popularity reports for plugins on only to then find out that no one enables it.

**Comment by cp2004** [comment]
# 🧹 *sweep* *sweep*
Don't mind me, just cleaning up old requests.
Now available on https://plugins.octoprint.org and within the plugin manager
