### ISSUE TITLE
[Request] Save temperature offsets through shutdown/restarts

### ISSUE THREAD

**Issue by jeffeb3** [OctoPrint/OctoPrint#2835]
The temperature offset is great, because I have two printers with the same filament, and they have different temperatures they like to print at, for various reasons. When I slice, I use the same profiles, and I just adjust the temperature offsets in Octoprint.

The trouble comes when I reset octoprint, or I turn it off and on again, and the settings are removed. 

It would be great if the settings were stored in the octoprint config file, and loaded on startup. Maybe there's room in the printer profile or temperature settings? You could then just set the temperature tab's offset value from the default, instead of starting at zero every time? WDYT?

**Comment by foosel** [comment]
I personally like the idea, but I'm not 100% sure if that wouldn't interfere with how some people are using the temperature offsets, as temporary offsets only, to be reset by a disconnect. In fact we had a bug a year or so ago where the profiles didn't properly reset, and that was causing some confusion.

So if that was implemented, it would need to be implemented such that there was some kind of checkbox in the offset editor, "persist" or something, and only if that was checked it would be saved.

**Comment by DanielJoyce** [comment]
You could have a 'floor' offset which is permanent, and then a 'tweak' that is volatile. And a button to add the 'tweak' to the floor and thus make it permanent. So it lets people dial it in during a print, and save it if they like.

**Comment by codejedi365** [comment]
@jeffeb3 I would recommend checking out the [FilamentManager](https://github.com/malnvenshorn/OctoPrint-FilamentManager) plugin if you haven't already.  I use it to remember the filament temperature offsets per spool.  As you know some manufactures have different temperature PLA standards (for example) and with this you can always slice at a single default PLA temperature while Octoprint handles the temperature offsets according to which filament is loaded (virtually).  It will then apply the offset to the gcode temperature automatically when printing & preheating.

Unfortunately, it does not include bed temperature offsets yet but I personally just requested that feature be added. [FilamentManager#142](https://github.com/malnvenshorn/OctoPrint-FilamentManager/issues/142)

Happy Printing!

@foosel, Since your users have had that confusion, I don't think it would be wise to add it to Octoprint core (although @DanielJoyce suggestion is smart) especially when there is already a plugin like FilamentManager to handle the offsets.  Thanks for all you do!
