### ISSUE TITLE
large gcode file upload fail

### ISSUE THREAD

**Issue by lomg** [OctoPrint/OctoPrint#308]
Hi, I'm having problems to upload large gcode files >200MB to octoprint, small filesizes work flawlessly. Always get "Upload failed
Could not upload the file. Make sure it is a GCODE file and has one of the following extensions: .gcode, .gco" but the file is .gcode

**Comment by salfter** [comment]
I've had the same issue with files larger than about 20 MB or so.  I watched the log file while an upload was in progress, but there were no entries made in the log when the upload failed.  There is a file in .octoprint/uploads with the same name as what I tried to upload, but it has about 5K of extra stuff tacked on.  I tried truncating it to the same length as the original file, but the SHA-1 sums don't match.  It would appear that longer files are getting corrupted somehow on upload.

If, after the failed upload, I scp the correct file into ~/.octoprint/uploads, the file will load and print properly.

If it makes a difference, I'm running the latest OctoPrint RC, installed on Raspbian.  I'm not using OctoPi.

**Comment by foosel** [comment]
@salfter this is a five year old ticket. OctoPrint has changed a *lot* since then, so please open a new full ticket (with logs, environmental information, reproduction steps etc). In case that you have a reverse proxy in place before your OctoPrint instance, please make sure though that you run into the same issues when accessing OctoPrint directly - if not, it's something off about your reverse proxy configuration.
