### ISSUE TITLE
Temperature set commands

### ISSUE THREAD

**Issue by TopherMan** [OctoPrint/OctoPrint#341]
With the current changes to support multiple toolheads, setting a temp sends the following:

```
M104 T<tool_num> S<target_temp>
```

However, on Smoothie, this fails to set the temperature. This is because Smoothie follows the official G-code standard, in which T is a separate command that changes the tool head, and as such interprets this T0 as a command to change tools, not as a parameter for M104. 

Some possible solutions: Change command to

```
T<tool_num> M104 S<target_temp>
```

which is what Smoothie folks recommend, and I believe that would work on Marlin.

Or make it configurable (and just default to M T S).

Or just make it not send the T at all if only one tool is defined.

**Comment by chorca** [comment]
Just wanted to mention, I know this is an old issue, but it causes some problems with Smoothie while printing with multiple extruders:
If you attempt to change the temperature of a non-operational tool while the printer is printing, it will switch to that tool and begin printing with it. This can cause a print to be scrapped and is kind of a dangerous thing since there's no warning that anything changes aside from the tool suddenly being used by the printer.
I know the idea is to have less options, but the only workaround is to wait until the tool is selected by the print job and set the temp while it's in use.

**Comment by foosel** [comment]
@chorca wait, do I understand that correctly, a `M104 T1 S220" will not only set the temperature for that toolhead but also make it the active one?

**Comment by chorca** [comment]
Yes, this command was sent when I changed the temp on T0 while T1 was printing:
`2017-10-18 04:47:56,165 - Send: N391102 M104 T0 S240*31`
and it caused the head to switch to T0 and begin executing the following Gcodes with that head. A quick change of the temperature of T1 caused it to switch back to the correct head after I noticed it was printing with the wrong head.

**Comment by foosel** [comment]
To be quite honest, that sounds like a bug in Smoothieware to me. As far as I know most slicers will use this format to preheat tools as well. If Smoothieware was reporting that it is Smoothieware as a response to `M115` it would be possible to work around this still, but it sadly doesn't even implement that command at all.

**Comment by digi2life** [comment]
I can confirm I'm having the same issue.

**Comment by Frans-Willem** [comment]
Same issue, any chances of having this fixed, or any known workarounds ?

**Comment by LazeMSS** [comment]
This should be reported as a bug on https://github.com/Smoothieware/Smoothieware as it is not a octoprint bug
