### ISSUE TITLE
[Request] Add button to navigation bar?

### ISSUE THREAD

**Issue by whc2001** [OctoPrint/OctoPrint#3507]
**Is your feature request related to a problem? Please describe.**
I am trying to add a custom button to the navigation bar (just like the settings and power dropdown button) which triggers a system command when clicked, but seems like there is no way to do that except writting a plugin?

**Describe the solution you'd like**
I wonder if it's possible to do something similar to the custom control tab, which I can simply write YAML to add a button to the navigation bar.

**Describe alternatives you've considered**
Maybe writting a plugin for specific this use case? But actually I wanted it to be versatile.

**Additional context**
I found a plugin called "Simple Emergency Stop" which can do this job, but the button text and command cannot be customized, and it only comes with EMC stop icon and triggers an M112 GCode command.

**Comment by foosel** [comment]
You are right in that the only way to do this is through a custom plugin, and this will also stay this way. The only reason why there are custom controls that are configurable via yaml is that this predates the plugin system. Going forward I'd prefer to have such extension points limited to plugins - one way to solve things instead of 20.
