### ISSUE TITLE
[Request] A working (python3.x) Filament Manager

### ISSUE THREAD

**Issue by kalleknall** [OctoPrint/OctoPrint#3509]
**Is your feature request related to a problem? Please describe.**
I use the Plugin FilamentManager for all of my Spools (~50), but there is no sign of activity and chance (for me) to get it work with python 3. 

**Describe the solution you'd like**
I think an Filament Manager should be a basic thing, because alls prints need Filament ;-)

**Describe alternatives you've considered**
Not to update... but that's not an real option for me :-(

**Additional context**
The FilamentManager Plugin has nice features but needs an archive funktion

**Comment by foosel** [comment]
I get the need, really, but please do not open requests that are about replacements for existing plugins here.

I've grandfathered in requests for non existing plugins simply because I haven't yet had a chance to migrate existing tickets on that to the forum, but new stuff and requests for adoption of an abandoned plugin (which this actually sounds like) should really better be posted on the affected plugins repository and the forum, plus possibly in the ticket system of the OctoPrint plugin repository.

The core OctoPrint repository is not the right place for this.

Python 2 is also not immediately thought to go away, and 1.4.0 does not require python 3, it merely supports running under it.
