### ISSUE TITLE
Version 1.5.3 Print Time Estimation

### ISSUE THREAD

**Issue by criton01** [OctoPrint/OctoPrint#4000]
Since upgrading to Version 1.5.3 the print time estimation is WAY off...  11.9mb file estimates at 2.5hrs
![octoprint1_5_3](https://user-images.githubusercontent.com/78521442/106842923-8478ae00-666a-11eb-800f-80c20739fc16.jpg)
 but print time while printing is in 2 days.

**Comment by jneilliii** [comment]
Notice the red dot, that means that estimation is not accurate. Recommend you look into the PrintTimeGenius plugin, as you will get far more accurate estimates than what's included by default in OctoPrint as it learns over time your specific printer and how fast it prints in real life. This isn't necessarily an issue, and because there is a red dot indicating inaccurate estimates for whatever reason (maybe the analysis didn't complete prior to starting the print), going to ho ahead and close this one. If you do think this is an actual bug, then please re-open the ticket with the full requested information in the issue template.

**Comment by criton01** [comment]
I’ll load the plugin just to check it out… it only happened AFTER upgrade to 1.5.3  I’ll get the template and submit if it’s a real problem.

Thanks for responding.

**Comment by cp2004** [comment]
Please always state what version you upgraded *from* as well as where you are at now. If you upgraded from 1.4.x then yeah there's been quite a few changes to OctoPrint. But if it was 1.5.2 -> 1.5.3 then no, only a couple lines changed relating to plugin install.
