### ISSUE TITLE
Artillery Sidewinder X1 Connection Failure

### ISSUE THREAD

**Issue by jlathrop1957** [OctoPrint/OctoPrint#4130]
### The problem

The terminal output says:
Changing monitoring state from "Offline" to "Detecting serial connection"
Performing autodetection with 0 port/baudrate candidates: 
Changing monitoring state from "Detecting serial connection" to "Error"
Changing monitoring state from "Error" to "Offline after error"

There have been several connection success: 1) Immediately after initial install I was able to start a print.  Some time later the print stopped.  At this time connection failed.  2) Someone in the community succeed with downgrade to version 1.4.2 and I tried that.  There was an initial connection success but then in time the connection failed.  

The current installation is and still failure to connect:
OctoPrint version : 1.6.0
OctoPi version    : 0.17.0

### Did the issue persist even in safe mode?

Yes, it did persist

### Version of OctoPrint

OctoPrint version : 1.6.0

### Operating system running OctoPrint

OctoPi version    : 0.17.0

### Printer model & used firmware incl. version

Artillery Sidewinder X1 as received.  I'm unsure of specifics.

### Browser and version of browser, operating system running browser

Chrome Version 90.0.4430.93 (Official Build) (64-bit), Microsoft Windows 10 Home, Version 10.0.19042 Build 19042

### Checklist of files to include below

- [X] Systeminfo Bundle (always include!)
- [ ] Contents of the JavaScript browser console (always include in cases of issues with the user interface)
- [ ] Screenshots and/or videos showing the problem (always include in case of issues with the user interface)
- [ ] GCODE file with which to reproduce (always include in case of issues with GCODE analysis or printing behaviour)

### Additional information & file uploads

[octoprint-systeminfo-20210508192256.zip](https://github.com/OctoPrint/OctoPrint/files/6446337/octoprint-systeminfo-20210508192256.zip)

**Comment by cp2004** [comment]
0 available candidates means that the underlying OS/hardware is not registering the printer at all. There's nothing Octo*Print* can do about this, this is beneath it, and is impossible to make work.

Your Pi is also reporting issues with overheating, so I suggest improving cooling. It is possible that if the USB chip gets too hot it shuts down.

Please seek support on the [community forums](https://community.octoprint.org) or the [discord server](https://discord.octoprint.org), since this is not a bug but support issue. We'll be happy to help troubleshoot the issue there.
