### ISSUE TITLE
[Request] Ability for plugins to customize the login page\process

### ISSUE THREAD

**Issue by Octo-Auth** [OctoPrint/OctoPrint#4253]
### Is your feature request related to a problem? Please describe.

Not related to a problem.

### Describe the solution you'd like

I would like for either the TemplatePlugin or UiPlugin to be able to influence or control the login.jinja2 page and relevant components.

My design goal is to create my own authentication provider bridge that can be used in **user_manager_factory_hook** to allow for third party identity stores.

### Describe alternatives you've considered

The UiPlugin -> **on_ui_render** does not fire on login page, even when **will_handle_ui** returns true. Maybe this is by design?

The TemplatePlugin doesn't have a **type** that matches the login page? 

- navbar
- sidebar
- tab
- settings
- generic

### Additional context

I'm trying to develop a plugin that implements third party identity store for authentication. This would require modifying the login page to support additional input controls besides just username and password. Very similar to LDAP authentication but is not LDAP based.

**Comment by cp2004** [comment]
> The UiPlugin -> on_ui_render does not fire on login page, even when will_handle_ui returns true. Maybe this is by design?

This is because by default you need to login to access the UI. For your UI plugin to replace the login page, it needs to requre *no permissions*. Can be done with an empty list of permissions for the UI, like so:

https://github.com/cp2004/OctoPrint-NextGen-UI/blob/818dbf3a2b92d5a65e5917443f7d75e1fd4efe60/octoprint_nextgenui/__init__.py#L46-L47

[And the docs for that are here](https://docs.octoprint.org/en/master/plugins/mixins.html#octoprint.plugin.UiPlugin.get_ui_permissions).

Then you will serve your custom UI conditionally from `on_ui_render` if no one is logged in, do whatever logging-in you need to make it happen from there, and then once the user is authenticated reload the page and *don't* serve your login page this time, so it goes through to OctoPrint's UI.

Hopefully that makes some sense...
