### ISSUE TITLE
Lost camera 

### ISSUE THREAD

**Issue by DickCrego** [OctoPrint/OctoPrint#4265]
### The problem

Lost camera with updated Octoprint from 1.6.0 to 1.7.0. Can I revert back to 1.6.0?

### Did the issue persist even in safe mode?

I cannot test this issue in safe mode (state why below)

### Version of OctoPrint

1.7.0

### Operating system running OctoPrint

Python 3.7.3 OctoPi 0.18.0

### Printer model & used firmware incl. version

Artillery Sidewinder X1 V4

### Browser and version of browser, operating system running browser

Firefox, and Apple Safari 

### Checklist of files to include below

- [X] Systeminfo Bundle (always include!)
- [ ] Contents of the JavaScript browser console (always include in cases of issues with the user interface)
- [ ] Screenshots and/or videos showing the problem (always include in case of issues with the user interface)
- [ ] GCODE file with which to reproduce (always include in case of issues with GCODE analysis or printing behaviour)

### Additional information & file uploads

![Octoptint Screenshot](https://user-images.githubusercontent.com/63127717/137592159-ff76acf6-4c49-41e9-aea7-b9ce94d2491b.png)

**Comment by jneilliii** [comment]
There are no known issues with the webcam. If you are going to report a bug, please include all requested information, specifically `Contents of the JavaScript browser console (always include in cases of issues with the user interface)` as that will help figure out what's going on here. Otherwise, if you really want to downgrade (not recommended), ssh to the pi and run the command `/home/pi/oprint/bin/pip install --force-reinstall --no-cache-dir OctoPrint==1.6.0`. The reason I say this is not recommended is because if this is an actual bug you're not helping in getting it resolved for the other users that may also be experiencing this issue.

**Comment by fieldOfView** [comment]
It actually looks like the camera image is showing up, but the image is just very dark. I think I see a red led in all that blackness.
In the community forums, people will likely be able to help you configure the exposure of the camera.

**Comment by DickCrego** [comment]
This is totally weird. Windows 10 Firefox browser PC#1 webcam does not show video. PC#2 with Firefox shows webcam video. iPad Safari does not show video. The webcam settings are the same on all devices. Octoprint 1.6.0 all them worked. V1.7.0 not all are working.

Dick
