### ISSUE TITLE
Progress bar print and missing percentage have the same value.

### ISSUE THREAD

**Issue by leoheck** [OctoPrint/OctoPrint#4325]
### The problem

I am seeing this ETA progress bar.
![image](https://user-images.githubusercontent.com/1277920/143689987-4714601c-8ef5-4c1b-99a1-f7942cbc1135.png)

I am not sure if this issue fits here or due to any plugin, unfortunately.

It shows the same percentage in the blue area and in the white area.
I believe this is a mistake

The blue area could show the percentage printed which I will call `p%`
And then, the other part could show the `(100-p%)%`, right?

### Did the issue persist even in safe mode?

I cannot test this issue in safe mode (state why below)

### If you could not test in safe mode, please state why

I am currently printing a long print.

### Version of OctoPrint

1.7.2 (Python 3.7.3)

### Operating system running OctoPrint

Raspbian GNU/Linux 9.13 (stretch)

### Printer model & used firmware incl. version

Creality Ender 3 (Custom Marlin 1.1.9)

### Checklist of files to include below

- [X] Systeminfo Bundle (always include!)
- [ ] Contents of the JavaScript browser console (always include in cases of issues with the user interface)
- [ ] Screenshots and/or videos showing the problem (always include in case of issues with the user interface)
- [ ] GCODE file with which to reproduce (always include in case of issues with GCODE analysis or printing behaviour)

### Additional information & file uploads

There are so many required things here, that is really hard for anyone to have the energy to report something. This should be easy for the end-user. This process overcomplicates the whole process. I was about to give up.

**Comment by cp2004** [comment]
There should only be one percentage value, in the middle of the progress bar:
![image](https://user-images.githubusercontent.com/31997505/143691494-67d87622-24aa-444e-9e6a-a05b99699952.png)

This is how it looks for me. After your print completes could you test it in safe mode? That would help us to determine if it is a plugin issue, and then find the issue faster once we know which plugin is causing the issue for you. Please also upload the systeminfo bundle to the issue form, so we can easily have all the log files in once place.

> There are so many required things here, that is really hard for anyone to have the energy to report something. This should be easy for the end-user. This process overcomplicates the whole process. I was about to give up.

Bug reports have to be more than just 'This broken, plz fix'. Uploading the system info bundle to the issue form takes you a few seconds, rather than the hours wasted by me having to now ask every bug reporter the above questions because I can't look into the bug report without all the information. Or you will just get 'It works for me, issue closed'
