### ISSUE TITLE
Custom controls output shows next to wrong button

### ISSUE THREAD

**Issue by arim215** [OctoPrint/OctoPrint#4329]
### The problem

I added 2 costum controls with output in my .octoprint/config.yaml file and both have regex filter.
When pressing the button for the first control with output, the output shows up next to the second button with the regex of the second button. But pressing the second button, all shows up correctl
![ynj3mx6aw6z71](https://user-images.githubusercontent.com/17930934/144543805-b66ba214-e0ea-491b-98bf-f930023e1b70.jpg)
y
![i17nlv6aw6z71](https://user-images.githubusercontent.com/17930934/144543808-785fa726-5c48-47c9-bd27-7396909032d3.jpg)
.

### Did the issue persist even in safe mode?

Yes, it did persist

### Version of OctoPrint

1.7.2

### Operating system running OctoPrint

OctoPi 0.18.0

### Printer model & used firmware incl. version

Ender 3 Pro - Marlin 2.0.x-bugfix

### Browser and version of browser, operating system running browser

Google Chrome

### Checklist of files to include below

- [X] Systeminfo Bundle (always include!)
- [x] Contents of the JavaScript browser console (always include in cases of issues with the user interface)
- [X] Screenshots and/or videos showing the problem (always include in case of issues with the user interface)
- [x] GCODE file with which to reproduce (always include in case of issues with GCODE analysis or printing behaviour)

### Addit
[octoprint-systeminfo-20211202230637.zip](https://github.com/OctoPrint/OctoPrint/files/7650221/octoprint-systeminfo-20211202230637.zip)
[config.yaml.txt](https://github.com/OctoPrint/OctoPrint/files/7712629/config.yaml.txt)

**Comment by cp2004** [comment]
Could you copy the custom controls configuration you are using? So that someone could try and reproduce the issue and figure out what's wrong. Don't share the whole of the config.yaml file as it contains secrets.

**Comment by arim215** [comment]
> 

I have put the "controls" portion of the config.yaml file in the original post, but here it is again (thank you for telling me not to put the hole file, as i originally did, but removed it
[config.yaml.txt](https://github.com/OctoPrint/OctoPrint/files/7655138/config.yaml.txt)
)

**Comment by foosel** [comment]
Your Z offset regex matches the output of `M92` as well, so OctoPrint doesn't know where it belongs. There are certain firmware builds out there which have a bug that cause commands to be acknowledged in a different order than received, which is why OctoPrint can't match up request/response through order and has to resort to pure pattern matching on received lines. In your case here that matching has an overlap, and your z-offset regex wins.

Try further specifying the regexes. Both response lines come prefixed with the command you sent, so also match against THAT.
E.g. for your E-steps, try (untested!):

```
M92.*?E([-+]?[0-9.]+).*?
```

and for your z-offset

```
M851.*?Z([-+]?[0-9.]+).*?
```

Always match as specific as possible.

Please report back on if this solves the issue.

**Comment by arim215** [comment]
I can confirm this fix works! thank you
