### ISSUE TITLE
Start and Stop MJPG-streamer

### ISSUE THREAD

**Issue by bubbasnow** [OctoPrint/OctoPrint#441]
I was trying to make some buttons that will start/stop the MJPG stream, 

`$ kill -9 'pidof mjpg_streamer'`

This will stop the service for a little bit then it starts up again automatically.. Anyone done this before and can post some help

thanks

**Comment by markwal** [comment]
Here's a script that works with OctoPi. Modified from Amedee's above but using the OctoPi's convention of using the pi user for running the daemon. (I'm not sure why the scripts are in the pi user's space. The reason for the script at all is to cover the other kinds of webcams.)  Don't use the eval from Amedee's script because then the calling script waits for the children to all quit which they never do because of the forever loop in the daemon.  And that will make OctoPrint stop working.

I'm sure you could also just use Amedee's script and location and just swap out the start and stop lines, but I went for the OctoPi convention and didn't try it the other way.  But definitely you'd need to get rid of the eval.

Put the following in /home/pi/scripts/webcam:

```
#!/bin/bash
# Start / stop streamer daemon

case "$1" in
    start)
        sudo -u pi /home/pi/scripts/webcamDaemon >/dev/null 2>&1 &
        echo "$0: started"
        ;;
    stop)
        pkill -x webcamDaemon
        pkill -x mjpg_streamer
        echo "$0: stopped"
        ;;
    *)
        echo "Usage: $0 {start|stop}" >&2
        ;;
esac
```

Then, in the system: section of /home/pi/.octoprint/config.yaml put the following:
```
   - action: streamon
     command: /home/pi/scripts/webcam start
     confirm: false
     name: Start video stream
   - action: streamoff
     command: /home/pi/scripts/webcam stop
     confirm: false
     name: Stop video stream
```

**Comment by AmedeeBulle** [comment]
There is no point in 'sudoing' to pi as this script is supposed to be run from the pi deamon, so it will always be run as the pi user.

Obviously for the location of the streamer software you can put it wherever it makes you happy. My view is that it had nothing to do with OctoPrint per say and can be used separately, which is why I put it in /usrl/local. But again it does not matter at all...

**Comment by markwal** [comment]
Oh yeah.  I grabbed that line from the OctoPi sources and assumed they'd done that on purpose because they were running from root.  So no sudo would be better.  And I agree with you on the location, I think I'd prefer /usr/local personally.

**Comment by cooley5758** [comment]
I've spent an entire day trying to get this to work, but it's almost like Octoprint isn't even recognizing the config.yaml file. I have no clue what I'm doing wrong.

**Comment by markwal** [comment]
By "almost like", do you mean the menu items don't show up or they don't do anything?  We should probably move this conversation to the google group since it is more like a support forum question than a github issue.  If the menu items aren't showing up in the system dropdown, they're in the wrong config.yaml, they're in the wrong part of config.yaml, they aren't indented properly or perhaps you didn't restart octoprint?

**Comment by cooley5758** [comment]
They're not showing up in any menu. I've got it in the config file in the user OctoPrint folder. I restarted octoprint several times, but I may not have it indented properly. The only settings I have in the file are for the webcam, and even the port settings don't show up on the menu.

**Comment by markwal** [comment]
I think you might be editing the wrong file.  There should be other settings in there from before you started messing around, like for shutdown and reboot, etc.  You're running an OctoPi image on a R.Pi right?  If so, the config file is /home/pi/.octoprint/config.yaml.  I'd ask you to upload it so I can look at it but you don't want to do that since it has a couple of secrets in it.  You could copy it somewhere locally, delete those lines or replace the secrets with "something something" and then upload it to gist.github.com and paste a link here.  Or better yet, start a thread here: https://groups.google.com/forum/#!forum/octoprint.  I'll watch for it.

**Comment by lukie80** [comment]
Unfortunately the webcam restarts after a dozen of seconds for both provided scripts. Now, I'm using a completely different solution which works fine for me. USB shutdown requests: [hub-ctrl](https://github.com/codazoda/hub-ctrl.c). It takes half a minute for the cam to be recognized again.

**Comment by HendrikRoth** [comment]
any idea how to stop the restart ? hub-ctrl is not suitable for me, i am using the raspberry camera.

**Comment by foosel** [comment]
While I can't help with the above comment by @HendrikRoth, current OctoPi distributions (I think starting with 0.12, definitely the current 0.13) have a proper initscript for the webcam service, so `sudo service webcamd start`, `sudo service webcamd stop` and `sudo service webcamd restart` should work out of the box and be suitable for use in OctoPrint's system commands (as long as the user has the right to execute that command via sudo).

**Comment by HendrikRoth** [comment]
Thanks, worked fine!
