### ISSUE TITLE
[Request] Show feedback if Github Access token is configured in UI

### ISSUE THREAD

**Issue by bruvv** [OctoPrint/OctoPrint#4520]
### Is your feature request related to a problem? Please describe.

https://github.com/OctoPrint/OctoPrint/issues/4519

### Describe the solution you'd like

Now when filling in the GitHub toke in the GUI there is no UI feedback. As a front end developer I would like to see some feedback that it did anything. Now it does not change whenever there is a key in `config.yaml` 

I would suggest to change the label of the input field:
![image](https://user-images.githubusercontent.com/3063928/169842305-d621b663-e015-49fd-b48d-fe73180ea5b5.png)
When you set it to "disabled" also the cursor will change to a red marker showing you you cannot edit it anymore.

```
<input type="text" class="input-block-level" data-bind="value: config_githubToken" placeholder="Token entered but hidden for privacy reasons" disabled="">
```

**Comment by cp2004** [comment]
Seems like a better solution, agreed. I don't think disabling the field should be done however, since that stops the token being replaced if it expires or a new one is generated. Would you like to create a PR?

**Comment by bruvv** [comment]
That is very true! I'll see what I can do.

**Comment by FedericoNembrini** [comment]
I am working on it.

Here are my considerations:
As far as I can see, the credentials are not retrieved from the configuration file because of this line of code
`return {"never": [["credentials"]]}`
Without retrieving the credentials, it is impossible to tell whether a token has been entered or not. The solution I'm thinking of is to remove the rule so that I can check for credentials and set a boolean flag, and then remove the credentials so that they are not exposed via the API, maintaining the current logic.

Also, is it not possible to remove an inserted token? I realised this because I can't find the config.yaml file, so I can't remove it.

**Comment by cp2004** [comment]
It may be possible to use something like [`on_settings_load`](https://docs.octoprint.org/en/master/plugins/mixins.html#octoprint.plugin.SettingsPlugin.on_settings_load) to replace the `credentials` section with boolean values rather than the actual credentials.

> Also, is it not possible to remove an inserted token? I realised this because I can't find the config.yaml file, so I can't remove it.

The only way would be through config.yaml at the moment - https://docs.octoprint.org/en/master/configuration/config_yaml.html explains where it is stored on most platforms. This may be in a hidden folder. That could be another PR with a 'delete' button 🙂

**Comment by FedericoNembrini** [comment]
Yes, I am currently doing tests using this:
```
data = dict(octoprint.plugin.SettingsPlugin.on_settings_load(self))
if "credentials" in data:
    data["github_set"] = data["credentials"].get("github", "") != ""
    del data["credentials"]
```

I could try inserting the boolean flag inside the "credential" dict to keep everything inside.

> The only way would be through config.yaml at the moment - https://docs.octoprint.org/en/master/configuration/config_yaml.html explains where it is stored on most platforms. This may be in a hidden folder. That could be another PR with a 'delete' button 🙂

I tried looking in the default folders but found nothing. Even with an extended search I couldn't find it. Really strange, even though I remember changing it a while ago.
