### ISSUE TITLE
Webcam preview in fullscreen and testmode display the vertical placed webcam view incorrect

### ISSUE THREAD

**Issue by dirkvranckaert** [OctoPrint/OctoPrint#4911]
### The problem

I have 2 webcams configured on my OctoPrint installation, twice the popular Logitec webcam C270.
One is installed horizontal (as you usually use these webcams). One however (due to limitations of my enclosure) is installed vertically. And I'm pretty happy with that installation direction since that gives me quite a different look at my printer :-)

But the problem is that on two places the webcam preview is not correctly displayed:
1. As you can see in the screenshot below I have rotated my camera through the settings with 90°, however if I press the preview button it does not rotate.
<img width="990" alt="Screenshot 2023-11-21 at 19 40 56" src="https://github.com/OctoPrint/OctoPrint/assets/4660794/5652ca25-1bad-43a6-ba4c-b0561425fff2">
<img width="595" alt="Screenshot 2023-11-21 at 19 41 47" src="https://github.com/OctoPrint/OctoPrint/assets/4660794/ab13ecc0-e72c-4182-bb7f-1d0a7cbb948f">
2. The regular preview inline is going good
<img width="1800" alt="Screenshot 2023-11-21 at 19 42 27" src="https://github.com/OctoPrint/OctoPrint/assets/4660794/cbf95976-fd49-4d12-a828-b2341f865854">
3. When I click the inline-preview for the fullscreen-view however it goes wrong, it does not scale the view to be fullscreen but instead the camera preview falls almost half off the screen...
<img width="1800" alt="Screenshot 2023-11-21 at 19 43 20" src="https://github.com/OctoPrint/OctoPrint/assets/4660794/a3d74475-722c-47a5-b150-4eae5b083b5f">
een view

### Did the issue persist even in safe mode?

Yes, it did persist

### Version of OctoPrint

1.9.3

### Operating system running OctoPrint

OctoPi

### Printer model & used firmware incl. version

Prusa MK4

### Browser and version of browser, operating system running browser

Chrome

### Checklist of files to include below

- [X] Systeminfo Bundle (always include!)
- [ ] Contents of the JavaScript browser console (always include in cases of issues with the user interface)
- [x] Screenshots and/or videos showing the problem (always include in case of issues with the user interface)
- [ ] GCODE file with which to reproduce (always include in case of issues with GCODE analysis or printing behaviour)

### Additional information & file uploads

[octoprint-systeminfo-20231121194555.zip](https://github.com/OctoPrint/OctoPrint/files/13429954/octoprint-systeminfo-20231121194555.zip)

**Comment by cp2004** [comment]
The option to watch the webcam in full screen is not part of OctoPrint core. Did you try it in safe mode?

**Comment by dirkvranckaert** [comment]
Safemode does not make any difference. Ok for the fullscreen view (I'll try to find out who's plugin that is then) but still the previews in the settings are not reflecting my settings.

**Comment by foosel** [comment]
The idea of the test preview is actually JUST to check whether the URL is correct, by embedding it directly with any kind of further processing. That's also why it's located next to the URL entry and not close to the rotation and flip settings. Changing that would basically require to duplicate the code already used in the control tab, which I'd rather not, and also make debugging more problematic - is the camera distorted due to a bug in the rotation/flip code, or because something's up with the camera? 

So this is working as it should here, and as already mentioned, the fullscreen view is not part of OctoPrint's core. That SHOULD probably react to the rotation and flip settings, however that needs to get reported to the plugin that provides that (maybe [Fullscreen Webcam](https://plugins.octoprint.org/plugins/fullscreen/)?).

As thus, I'm closing this since I don't see anything actionable here.
