### ISSUE TITLE
[Request] Add 'Connected' state mark to the temperature graph

### ISSUE THREAD

**Issue by cp2004** [OctoPrint/OctoPrint#4921]
### Is your feature request related to a problem? Please describe.

The temperature graph starts out of nowhere in OctoPrint 1.10.0

### Describe the solution you'd like

With the temperature graph now being stuck to 30 minutes, I think it might look nice to have a line & a mark at the start of the temperature graph when it starts to move. Not hugely important, but this also should not be too difficult. I'd add it myself but not sure where it goes and don't have time to find out yet :/

### Describe alternatives you've considered

None

### Additional context

![image](https://github.com/OctoPrint/OctoPrint/assets/31997505/7acb1465-e1a6-4b39-8120-8e75091c0836)

**Comment by foosel** [comment]
Great idea!

![image](https://github.com/OctoPrint/OctoPrint/assets/83657/16cf782c-d245-4800-bd6e-983db0c10c81)

I've also added a marker for the Disconnect event. 

While doing that I noticed that I still have an issue now because the chart no longer moves after disconnect, which in theory is of course fine, but that also means the time line isn't updating and thus getting wrong the longer you are disconnected... need to fix that. 

Anyhow, this request will be implemented in 1.10.0
