### ISSUE TITLE
Embedded devices should not be phoning home, nor a priest for the cult of notifications

### ISSUE THREAD

**Issue by allanonmage** [OctoPrint/OctoPrint#4944]
### The problem

Poignant words to m
[Octoprint System Bundle.zip](https://github.com/OctoPrint/OctoPrint/files/14158706/Octoprint.System.Bundle.zip)
ake my point across the vast interdimensional void known as The Internet, crossing languages and ideologies.  My point is you to force you to understand what I am saying.  If you disagree, that's fine.  Most internet people don't understand, so I'm being especially forceful and direct on purpose here.  These are design-decision bugs, but they are still bugs.  At best, you can call them anti-features.

I like your software, and use it often.  However, the software becomes an embedded system, and you are misunderstanding how embedded systems are expected to work.  I work with embedded systems professionally.  Embedded systems should not be calling home all the time with no way to turn that off.  If fine if you want to do that by default, since most users presumably like that.  However, the fact that you can't disable it in its entirety is a problem.  A major problem.

As the people who [discussed this years ago](https://community.octoprint.org/t/disable-important-announcements/21651) point out, by insisting on a connecting to your servers, you are forcing a risk of some hacker being able to take control of the printer and cause a house fire.  If you didn't force a connection to your servers, you would not be complicit in said housefire.  [Someone else](https://community.octoprint.org/t/disable-calling-home-for-anything-including-updates-or-announcements/42141) mentioned this also.

This is vague, what am I talking about?  I connected to a servers for the first time in a while, and powered on one that hadn't been powered on for a while.  POPUPS EVERYWHERE.  Pop ups are bad!  They are a cult in the world of programmers, and a disease (a plague even!) upon the world.  They are abused more than the main character of an dark and gritty anime.  I had SO MANY popups on my embedded plastic melting server UI..... OMG!!!111

One of the popups is "Important Announcements", which was present on both servers.  One of the servers had all the other announcements turned off, another did not.  "Important Announcements" is not turn off-able, and goes to your server, which is what the first few paragraphs are about.  There is no reason it should not be turn off-able.

The servers are running 1.6.1 and 1.9.3 and neither can turn these off.

Now, a word about popups:

POPUPS  ARE BAD MMMMMMMMMKAY

NO SERIOUSLY GET YOUR POPUPS OUT OF MY WAY I'M TRYING TO STOP A THERMAL RUNAWAY!!!!!!!!!!!!!!!!1111111

### Did the issue persist even in safe mode?

Yes, it did persist

### If you could not test in safe mode, please state why ("currently printing" is NOT an excuse!)

n/a

### Version of OctoPrint

Multiple

### Operating system running OctoPrint

Raspberry Pi image from OctoPi

### Checklist of files to include below

- [X] Systeminfo Bundle (always include!)
- [ ] Contents of the JavaScript browser console (always include in cases of issues with the user interface)
- [ ] Screenshots and/or videos showing the problem (always include in case of issues with the user interface)
- [ ] GCODE file with which to reproduce (always include in case of issues with GCODE analysis or printing behaviour)

### Additional information & file uploads

n/a

**Comment by cp2004** [comment]
You certainly could have made this point without so much... noise? And it would probably make people take you more seriously.

Important announcements exist to safeguard both the project & it's userbase. In the case that an important announcement is required, the project maintainers would like to be able to communicate this to as many people as possible.

You can disable the 'Announcements' plugin in it's entirety from the plugin manager, so I do not see a problem here. You can disable it if you would like to, and your issue is solved. I was typing out a longer answer, to explain it, before being reminded how simple it was by [my answer in the thread that you linked](https://community.octoprint.org/t/disable-calling-home-for-anything-including-updates-or-announcements/42141).

> As the people who [discussed this years ago](https://community.octoprint.org/t/disable-important-announcements/21651) point out, by insisting on a connecting to your servers, you are forcing a risk of some hacker being able to take control of the printer and cause a house fire.

If you re-read this thread that you have linked as well, the discussion is actually about how *not updating* your OctoPrint instance leaves you vulnerable to discovered security flaws, and that the important announcements were used to communicate this. If you are isolated from the news, you will not know if you are vulnerable. It is the opposite to your claim.
