### ISSUE TITLE
Octoprint inaccessable after a few days of inactivity

### ISSUE THREAD

**Issue by antonangov** [OctoPrint/OctoPrint#4970]
### The problem

1. Octoprint is active, but the 3d printer is not used for a prolonged period of time
2. When trying to access it, I get error 500 on the webUI
3. After reboot it works for a few days, until the same issue appears

### Did the issue persist even in safe mode?

I cannot test this issue in safe mode (state why below)

### If you could not test in safe mode, please state why ("currently printing" is NOT an excuse!)

The issue disappears after reboot

### Version of OctoPrint

OctoPrint 1.9.3

### Operating system running OctoPrint

OctoPi 0.18.0

### Printer model & used firmware incl. version

Longer LX4 Pro, Marlin 2.x.x

### Checklist of files to include below

- [X] Systeminfo Bundle (always include!)
- [ ] Contents of the JavaScript browser console (always include in cases of issues with the user interface)
- [ ] Screenshots and/or videos showing the problem (always include in case of issues with the user interface)
- [ ] GCODE file with which to reproduce (always include in case of issues with GCODE analysis or printing behaviour)

### Additional information & file uploads

[octoprint_error_15_mar_2024.txt](https://github.com/OctoPrint/OctoPrint/files/14616914/octoprint_error_15_mar_2024.txt)
[octoprint-systeminfo-20240315143510.zip](https://github.com/OctoPrint/OctoPrint/files/14616927/octoprint-systeminfo-20240315143510.zip)

**Comment by foosel** [comment]
Your log is absolutely spammed with errors from your influx plugin which appears to be misconfigured. Additionally there were some big issues at the start of the log that looked like the underlying os ran out of resources. And your system was reporting having reached the soft temperature limit as well.

I suggest you improve cooling, reboot, restart in safe mode, use it like this for a while. If you can then no longer reproduce the problem, one or more of your many installed third party plugins is to blame. Otherwise, please get in touch on the [community forums](https://community.octoprint.org) as this looks very much like an issue specific to your environment and this a support issue and not a general bug (also given that thousands of OctoPrint devices, my own included, run stable for months without active use, based on anonymous usage statistics).
