### ISSUE TITLE
File analysis is blocking the file list API call

### ISSUE THREAD

**Issue by ckuethe** [OctoPrint/OctoPrint#5078]
### Is your feature request related to a problem? Please describe.

I'm frustrated at how long it takes for the file manager to load while it's running background analysis. Depending on the file being processed it can take in excess of 5 minutes for the file list to load. This happens both over the web ui and the API (octodroid).

### Describe the solution you'd like

1) Don't block the list of files while analysis is running. 
2) Cache the analysis results to avoid unnecessary reprocessing.

### Additional context

`2024-11-06 16:23:38,498 - octoprint.filemanager.analysis - INFO - Analysis of entry local:TankardCaddyRemix_PLA0.2mm.gcode finished, needed 321.60s`

**Comment by foosel** [comment]
This is actually a bug. The analysis is supposed to happen in the background without blocking the list in any way.

> Cache the analysis results to avoid unnecessary reprocessing.

Once an analysis is finished, it *should* be put into the metadata of a file and thus cached. If a file constantly gets re-analysed, that's because the analysis fails for some reason, and that should be reported as a separate bug please, including the file with which to reproduce the behaviour and a current system info bundle.

The file API itself as well as the internal file manager also have quite some caching, exactly to NOT do work more than once and keep things running smoothly. This of course also depends on the underlying hardware, the amount of files etc.
