### ISSUE TITLE
[Request] LDAP User Integration

### ISSUE THREAD

**Issue by thinkl33t** [OctoPrint/OctoPrint#594]
We use OctoPrint in our hackerspace to control our 3D printers.  Currently we're doing this through a User and Maintainer account, with a shared password.

Ideally we'd like to have OctoPrint authenticate against our LDAP server, with group-membership requirement for logging in.  So anyone in the '3D Printer Users' group would be a user, and anyone in the '3D Printer Maintainers' would be a maintainer.

**Comment by rcopley** [comment]
Most of this can already be done using Nginx as a reverse proxy for the Octoprint (although I can't think of a way to support tiered access using this method currently). Once the module is configured, you can disable access control on the Octoprint interface (since nginx would then provide authentication).

Check out https://github.com/kvspb/nginx-auth-ldap for info on the Nginx module. There's been a couple other issues where authentication tweaks have been brought up and the impression I go was that it's a lower-priority item (because it would require some major changes with small additional benefit). You can read up on some of the thoughts on authentication at issue #640.

I'm working on a guide and a set of Nginx configurations that might make it easier to configure and Octoprint instance to be protected by nginx. I can probably add a configuration to make it easier to support LDAP as well.

**Comment by MaitreDede** [comment]
Hi,
I would be pleased to have this feature too, but the reverse proxy is not a solution for me.

In my case, here is what I would like :
- LDAP integration (active directory) for web access authentication
- mapping of LDAP groups for permissions (like #1110)

So the printers access are protected using users' own credentials.

**Comment by gddeen** [comment]
Due to access from Octoprint by others, I had put a command to lock/unlock in the firmware. But this stuff didn't provide much protection. (Unless serious time changing access keys were used where anyone could view the content...) I also just 'hacked' it into Firmware with no thought.

**Comment by ophilli** [comment]
Not sure how feasible this would be with LDAP, or if it would even be useful- but you could possibly write a script that copies LDAP users into Octoprint with the API calls. http://docs.octoprint.org/en/master/api/users.html

**Comment by MiggyMan** [comment]
Just my 2cents here but the problem with doing it that way is that you have a sync delay that might cause problems with  disabling accounts and if you wanted to sync passwords you'd need to store them in un-encrypted in the ldap tree (or weakly encrypted) and no admin with his salt will do this.

But you could take a hybrid approach, sync the usernames across but authenticate against ldap, if you could store the full distinguished name for the user in octoprint it would make login easier otherwise you'd need to either provide the full dn *or* set up the tree to allow anonymous searching on the uid attribute to determine this from just the username.

**Comment by pook0959** [comment]
This would be a feature that would go a long way since the 3d printer was provided by our work. another suggestion in addition to using ldap authentication, is the ability to keep track of who is printing what and a notification of who started the current print.

**Comment by foosel** [comment]
I just realized that I apparently managed to never comment on this ticket but only talked about it on IRC m( 

Sorry.

Thing is, right now it would already be possible by implementing a custom version of [octoprint.users.UserManager](https://github.com/foosel/OctoPrint/blob/master/src/octoprint/users.py#L23) that would rely on a different source than `users.yaml` that the [FileBasedUserManager](https://github.com/foosel/OctoPrint/blob/master/src/octoprint/users.py#L193) uses as backend. Which user manage class to use can already be specified through `accessControl.userManager` in `config.yaml`, see also [the docs here](http://docs.octoprint.org/en/master/configuration/config_yaml.html#access-control).

What might be interesting would be to open this up to make it a bit more accessible (read: allowing plugins an easy way to provide custom user managers).

**Comment by battis** [comment]
FWIW, I noticed that [OctoPrint-LDAP](https://github.com/gillg/OctoPrint-LDAP) apparently tries to do what @foosel suggests. I haven't been able to get it working properly with our LDAP server, but the outlines (at least) should be there?

**Comment by battis** [comment]
> FWIW, I noticed that [OctoPrint-LDAP](https://github.com/gillg/OctoPrint-LDAP) apparently tries to do what @foosel suggests. I haven't been able to get it working properly with our LDAP server, but the outlines (at least) should be there?

After some fiddling around, [I have a fork of the aforementioned plugin](https://github.com/battis/OctoPrint-LDAP) that is working well for us.

**Comment by gillg** [comment]
Thanks to @battis and @paulkstelis !
They made a new working version of https://github.com/gillg/OctoPrint-LDAP.
 I think it closes this issue... ?

**Comment by cp2004** [comment]
It does, and it is due to be on the official repository soon. Thanks for bringing this up.

**Comment by jneilliii** [comment]
Yeah, once we figure out how to handle the external apt dependencies, @battis fork will be registered.
