### ISSUE TITLE
[Request] Power consumption on graph

### ISSUE THREAD

**Issue by fjriosp** [OctoPrint/OctoPrint#647]
It could be nice to show the power consumption on the graph (like in repetier-host):

![repetier8](https://cloud.githubusercontent.com/assets/6414473/4975247/4b91a756-68d6-11e4-9aaa-96abb529c8d4.png)

My current output to the M105 command is:
Recv: ok T:259.0 /260.0 B:89.8 /90.0 T0:259.0 /260.0 @:26W B@:118W

I'm using Marlin with Watts output enabled.

Thanks a lot

**Comment by Quas7** [comment]
Not sure, if there is already a plugin/feature for Octoprint. Possible, that I did not find it yet.

Nevertheless, there is a valuable usecase for graphing PWM% of hotends in or below the temperature graphs: 
--> PID overshot reduction.

Some very strong (40W on MK8) hotends require restriction of PID-Power and a larger PID control 
 temperature window. Otherwise ABS/PETG or other higher temperature filaments get burned during ramp up (=clogging) besides faster wearout of the PTFE fitting.

This is controlled in marlin by setting in configuration.h:
#define PID_MAX 205  #255 = full PWM%
#define PID_FUNCTIONAL_RANGE 110  #Temperature window for PID control (for lower temperatures = 100% PWM)

Set temperature 210°C --> at 100°C PID power is reduced to 205/255% and PID takes over control

This reduces overshoot to a great extend. But, you do not want to hit the power reduction limit during normal PID operation! 
Therefore, you need the PWM% or power in a graph. 
It is also possible to export the log and graph the watt-output from marlin - but this is not "live" feedback to tune P, I and D values.

**Comment by Salandora** [comment]
Thanks to @Quas7 I really need to say +1 here...
But I would say it shouldn't be a cire feature but a plugin because it is nothing you would need all the time. It could be put into an own Tab with some text boxes for P, I and D and some more stuff like Set Temperature
So it would become easy to fine tune the values.
Maybe also include some descriptions for the values.
Also take into account that on Repetier you could also use the dead time method instead of pid.

**Comment by JohnOCFII** [comment]
There is a plug-in that shows power usage (estimated).  You might start with this author and his plug-in to achieve what you want.  http://plugins.octoprint.org/plugins/stats/

**Comment by Salandora** [comment]
@JohnOCFII If I'm not misunderstanding the plugin, it is using predefined values to calculate the power consumption or?

I think this one here is an easier start point: http://plugins.octoprint.org/plugins/tempsgraph/
It already plots the graph for the temps, so one would only need to add a graph for the power, after extracting the necessary values from the M105 output.

**Comment by Quas7** [comment]
Yes @Salandora. A Plugin would be the best option.

@JohnOCFII is right. The plugin uses predefined W/h values to estimate. Also, "power" is not the right value, I would say.  We are looking for the PID controller _setpoint_ (0...255) in % for example.

This is the terminal log output during ramp up from my printer (Marlin 1.1.3)
Recv:  T:208.32 /208 B:60.29 /60 **@:11** B@:127 W:7

T:actual/setpoint B:actual/setpoint **@:xx/255** B@:xx/127 W:power

The "only" thing, that needs to be graphed is "@:xxx" in % (255=100%) together with the temperature measurments.
